### ISSUE TITLE
Stomp version for this bundle

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/RabbitMQBundle#1]
Hi Matthias. I want to use these SimpleBus libraries but currently I am using ActiveMQ instead of RabbitMQ. I think it would very easy to add support for Stomp (https://stomp.github.io/). This way your library could be used with all these MQ systems: https://stomp.github.io/implementations.html

I think you only have to split my implementation https://github.com/josecelano/ddd-symfony-sample/blob/master/src/Matthias/Common/App/MessageQueue/StompMessageQueue.php into Publisher and Consumer and make it better :-) (for example adding tests).

Anyway I am going to do it. I will send you a link when I am finished.

In case you want to do it I can help you with ActiveMQ. I am not an ActiveMQ expert but for example I can give you access to my test ActiveMQ server so you can test the library without having to install your ActiveMQ server.

**Comment by matthiasnoback** [comment]
Great, you can do that quite easily I think. I've tried to remove as much logic as possible from the publisher and consumer, and instead pushed that out to default/standard functionality implemented inside the Asynchronous library (see https://github.com/SimpleBus/Asynchronous/blob/master/src/Message/Envelope/Consumer/StandardSerializedEnvelopeConsumer.php and https://github.com/SimpleBus/Asynchronous/blob/master/src/Message/Envelope/Serializer/StandardMessageInEnvelopeSerializer.php).

**Comment by josecelano** [comment]
In fact, I did not like my implementation and becuase it is not my core domain I tougth I could wait for you to release a better solution :-)

You are doing a great contribution to PHP community. I do not know a better library to implement CQRS pattern in PHP. Thanks. I hope I can contribute at least with Stomp support.

**Comment by matthiasnoback** [comment]
Wow, thanks for your kind and encouraging words!

**Comment by mseshachalam** [comment]
Isn't this bundle an implementation of AsynchronousBundle with RabbitMQ. @josecelano (Not sure if I am correct) May be you can use AsynchronousBundle with anything that supports pub/sub. @matthiasnoback I follow your code. It is the guideline I follow to write mine. Waiting for your DDD application.

**Comment by josecelano** [comment]
@mseshachalam yes, it is. I will add another implementation with Stomp (which supports pub/sub). Here I am asking for the new implementation to be "official" in the SimpleBus GitHub organization as I think people can use the library easily with a lot of MQ systems.
In fact I am going to Copy/Paste this bundle and adatp it to use Stomp PHP library  (https://github.com/dejanb/stomp-php) instead of RabbitMQ.

:+1: DDD application

**Comment by matthiasnoback** [comment]
@josecelano Yes, it makes sense so have other adapters in the same organization.
@mseshachalam Yes, this bundle offers specific implementations for AsynchronousBundle. I'd have prefered a separate bridge/library for RabbitMQ (without the Symfony stuff), but it turned out that the classes/interfaces that I needed were inside OldSoundRabbitMQBundle. Also, thanks for your kind words. And I am still working on the sample application :)

**Comment by matthiasnoback** [comment]
@josecelano Is it okay if I close this issue for now? If you want to contribute your library/bundle to the SimpleBus organization, just let me know.

**Comment by josecelano** [comment]
It´s OK for me.

I am working on other stuff now but when I finish I will upgrade my DDD sample to use your new version and I will add a bundle for Stomp support. Then I will notify you.

**Comment by matthiasnoback** [comment]
Okay, thanks again for your input/questions!
