### ISSUE TITLE
Define different consumers

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/RabbitMQBundle#3]
Do you have a way to have different consumers for specific commands or handlers? We have a lot os situations that we are doing some heavy processing to generate videos and upload them to Youtube for instance. But also have some commands that are being handled in no time at al and we don't want the video processing commands slow down the simple commands.

**Comment by matthiasnoback** [comment]
Interesting suggestion! I think the solution would be to use routing keys, right? This would be my proposal:

- The class of every message is converted to a routing key (I think `str_replace('\\', '.', ...)` would do the trick).
- This generated routing key is added when a message is published.
- If the type of queue is a topic queue, you can then run anonymous consumers for a specific routing key, or subset of routing keys (i.e. message types) - see also https://github.com/videlalvaro/RabbitMqBundle#anonymous-consumers

**Comment by cmodijk** [comment]
What we currently have is a default consumer for the fast commands / events I don't know if with this proposal you can have a default one and different keys for specific commands. But I do think that using routing keys is the way to go. What we currently do is let the message define the routing key using our [AdvancedAsyncMessage](https://github.com/JCID/RabbitMQSimpleBusBridge/blob/master/src/MessageBus/AdvancedAsyncMessage.php) interface. 

But I think it is better to allow this to be defined from the dependency injection tag's. But I don't know how hard this would be to define different keys.

**Comment by matthiasnoback** [comment]
Ah yes, this is where I decided to take another direction - I didn't want to define any of these infrastructural concerns inside the message classes themselves. Still, I totally think you have chosen the more pragmatic solution :) Also, you're done faster than I am!

**Comment by matthiasnoback** [comment]
Hmm, I didn't get this topic thing working - will try some more later.

For now I found out that you can use [fair dispatching](https://github.com/videlalvaro/RabbitMqBundle#fair-dispatching) to divide the load between several consumers.

**Comment by matthiasnoback** [comment]
Ha, it works. But it requires a little bit of setup, which is now half-automatically done by the bundle: http://simplebus.github.io/RabbitMQBundle/doc/routing.html

**Comment by matthiasnoback** [comment]
I think this solves the issue, can you confirm @cmodijk?

**Comment by cmodijk** [comment]
Yeah! Asome! The only thing I have to think about is that RabbitMQ duplicates a message it it matches multiple keys and if you are handeling commands you want only one handler to handle the command. And I would like to specify the key for some cases and not do it based on the class. Is it already possible to have a custom routing_key strategie?

**Comment by matthiasnoback** [comment]
Just added the option to configure your own resolver service for routing keys: http://simplebus.github.io/RabbitMQBundle/doc/routing.html#custom-routing-keys

I really appreciate your suggestions by the way! If anything else is missing, just let me know. You are the ones with production experience after all :)

**Comment by matthiasnoback** [comment]
I don't know how to tackle the duplicate message thing by the way... If you have some ideas, just let me know. Not sure even if this library should do it.

One other thing: do you use the options array when publishing messages? It's currently always omitted, but is this something you determine at runtime, or would a configured array suffice? Or is it just not needed at all?

**Comment by cmodijk** [comment]
Cool! We would really like to have one combined effort to use one library for SimpleBus and RabbitMQ. And for every sugenstion i make i want to add a pull request but time after time you have already implemented it and that's amazing! And I really like your implementation using JMS serializer I never thought on using that.  

I think the duplicate message should be something to document and not fix it should be up to the implementer to know that this is the case with RabbitMQ. We currently do not use this implementation we use different producers and exchanges for every command that is running longer than a few seconds. But it feels really strange to have al of these exchanges. We were investigating to implement it using routing keys but we have not got the time to implement this. 

What do you mean with the options array? Do you mean the additionalProperties? If yes than no we do not use these. 
* https://github.com/videlalvaro/php-amqplib/blob/master/doc/AMQPMessage.md#supported-message-properties

When do you think you could tag the Async an RabbitMQ bundles as stable?

**Comment by matthiasnoback** [comment]
Sounds all very good to me!

About the custom routing key resolver: you can always inject the class based resolver service if you want.

Yes, I was talking about the additionalProperties thing. I don't know about a use-case, so I'll leave them out for now.

**Comment by cmodijk** [comment]
I think we could close this right?
