### ISSUE TITLE
Possibility for Acknowledgements

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/RabbitMQBundle#4]
RabbitMQ allows to have different responses to Acknowledgements if a message is handled correctly. I think we should try to support this also for commands and event. But i'm not sure how we should allow this using commands and events. This is related to #2 to retry messages if it fails for some reason.  

Consumers can return any of these 
* https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/ConsumerInterface.php

**Comment by matthiasnoback** [comment]
My thoughts so far: if you don't acknowledge an AMQP message, it will be dispatched again and again until it is finally acknowledged. This means that we shouldn't return false or something from the consumer. Instead, implementing your own error handler is the way to go in case you want to publish a message again some other time.

**Comment by matthiasnoback** [comment]
By the way, I have left the `RabbitMQConsumer` class particularly clean, so users can always implement their own logic, without duplicating any code.

**Comment by cmodijk** [comment]
The only thing we are doing is when we get an exception is to send the [reject](https://github.com/JCID/RabbitMQSimpleBusBridge/blob/master/src/MessageBus/DefaultConsumer.php#L65) response which tells RabbitMQ to remove / discard the message but not define it as handled.

**Comment by matthiasnoback** [comment]
Ah, that's a good suggestion. I will add it.

**Comment by matthiasnoback** [comment]
Done: https://github.com/SimpleBus/RabbitMQBundle/blob/master/src/RabbitMQMessageConsumer.php

**Comment by matthiasnoback** [comment]
Closing this (feel free to add more comments though, I'm just cleaning up a bit to keep track of the issues).
