### ISSUE TITLE
Please rename the project

### ISSUE THREAD

**Issue by videlalvaro** [SimpleBus/RabbitMQBundle#6]
There's already a quite old bundle for Symfony called RabbitMqBundle[1]. Even if your bundle has a different namespace, I think it just adds confusion for its users. 

1 - https://github.com/videlalvaro/RabbitMqBundle

**Comment by ruudk** [comment]
I don't agree. There always will be name collisions. That why we have namespaces :)

**Comment by videlalvaro** [comment]
The issue here is not what your code can solve using namespaces, but what
people expecting to find my bundle will do when arriving at this project.

My Bundle is pretty well established inside the Symfony community. Besides,
we already argued quite a lot on Twitter about this issue.

**Comment by ruudk** [comment]
I'm not @matthiasnoback ;)

**Comment by videlalvaro** [comment]
Please. Can you cut it with this? I had enough over the weekend. I'm not
stupid and I can read as well, so I can easily tell you are not Noback.
Perhaps this is funny to you. It is not funny to me.

**Comment by ruudk** [comment]
![o my](http://i.giphy.com/vA5evXPactVhC.gif)

**Comment by cmodijk** [comment]
@videlalvaro Could add a link to the twitter stream about this? I'm very interested in reading the arguments.

**Comment by videlalvaro** [comment]
@ruudk wow. Really mature. Where do I go so I can clap to you in person. 

@cmodijk TL;DR we agreed with @matthiasnoback that a name like RabbitBridge or something like that would better fit this project.

The scope of this project is totally unrelated to that of the original RabbitMQBundle, I'd imagine someone being recommended to use my bundle, landing in this project, and then deciding to opt for other tech based on this particular bundle not meeting the original requirements.

I don't care if _this_ project better solves certain users needs, and therefore they use this instead of the original RabbitMQBundle; I just want to avoid confusion.

**Comment by ruudk** [comment]
@videlalvaro You must have had a hell of a weekend... good luck... I was just giving my opinion as I use SimpleBus bundles too.

**Comment by ceesvanegmond** [comment]
I agree with @videlalvaro on this one. Why not rename the project to 'RabbitMQBridge' or something.
I think it makes more sense.

@ruudk Dont bash man... that's just rude.

**Comment by cmodijk** [comment]
I totally agree to rename the project to RabbitBridge I think it's a better fit for what it does. Also because it's bridging @videlalvaro bundle with SimpleBus.

**Comment by videlalvaro** [comment]
@ruudk give as many opinions as you want, but don't treat me like I'm stupid.

**Comment by matthiasnoback** [comment]
Guys, guys! I already agreed that the name should be changed :) just didn't
get to it yet. I will do it asap. I will also change the name of my
JMSSerializerBundle because of the same reasons. I should have thought
harder about proper names.
Op 17 mrt. 2015 14:05 schreef "Alvaro Videla" <notifications@github.com>:

**Comment by videlalvaro** [comment]
@matthiasnoback :+1:
